# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "100", "image" => "bento/ubuntu-16.04"},
  "node01" => {"memory" => "1024", "cpu" => "1", "ip" => "101", "image" => "bento/ubuntu-16.04"},
  "node02" => {"memory" => "1024", "cpu" => "1", "ip" => "102", "image" => "bento/ubuntu-16.04"}
}

Vagrant.configure("2") do |config|
	config.ssh.username = "vagrant"
	config.ssh.password = "vagrant"
	config.ssh.keys_only = true
	config.ssh.insert_key = true

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "hyperv" do |vb|
        vb.vmname = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
	  config.vm.synced_folder "./home/","/remote/home/",
	  type: "smb", smb_password: "omitido",
	  smb_username: "omitido", create:true
      end
      machine.vm.provision "shell", path: "hiperv.sh"
      machine.vm.provision "shell", path: "docker.sh"
      
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end

    end
  end
end
